= Complete Private Server Setup for E-Mail, Cloud and more
 
Here I describe my server setup, which provides the following services:

* E-Mail (https://mailcow.github.io/mailcow-dockerized-docs/[Mailcow])
* Cloud (https://www.seafile.com/en/home/[Seafile])
* Dynamic DNS (https://github.com/dprandzioch/docker-ddns[dprandzioch/docker-ddns @ Github])
* OpenVPN (https://github.com/kylemanna/docker-openvpn[kylemanna/docker-openvpn @ Github])
* Offside Backup (https://borgbackup.readthedocs.io/en/stable/[Borg Backup])
* A simple HTML Webpage

This Setup is set behind http://www.haproxy.org/[HAProxy] and https://letsencrypt.org/[LetsEncrypt]. And is deployed with https://docs.docker.com/[Docker] and https://docs.docker.com/compose/[Docker-Compose], to keep it as simple as possible.

I'm not a professional administrator and I run this setup privately only.

This is not supposed to be a copy&paste tutorial, but will probably work as such as well.

== Requirements

* Server with a static IP Address
* Domain
* Little Home Server for Offsite Backup (Raspberry PI/Intel Nuc/Hetzner Storagebox)

I'm using a VPS (virtual private server) from https://contabo.com/?show=vps[Contabo], called 'VPS L SSD' and a Intel NUC, both with Debian 10.

== Setup
=== Docker installation

First we need to install Docker and Docker-Compose.
These steps are well documented on the official docker website, so I will just link to them.

https://docs.docker.com/install/linux/docker-ce/debian/[Docker]

https://docs.docker.com/compose/install/[Docker-Compose


Beginning with HAProxy 
=== Let's Encrypt/Certbot installation
Just like with Docker, there are enough instructions to install https://certbot.eff.org/[certbot].


=== Folder Structure and Preparation
Create folder structure (you can customize the location if you want) and download the required files.
[source,bash]
----
git clone https://github.com/oyren/yet_another_complete_groupware_setup /root/docker
git clone https://github.com/mailcow/mailcow-dockerized.git /root/docker/mailcow-dockerized
----


=== Configuration
Inside the `web` folder, you will find the `docker-compose.yml`.
I will split the files into parts to explain them, you have to replace `example.com` with your own domain and make other adjustments if necessary. 

==== HAProxy

Beginning with *HAProxy*, which we will use as a reserve proxy and which takes care of SSL.

.docker-compose.yml
[source,yml]
----
version: '3.5'
services:

        haproxy:
                container_name: haproxy
                image: haproxy:latest
                ports:
                        - "80:80" # <1>
                        - "443:443" # <2>
                volumes:
                        - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro # <3>
                        - ./example.com.pem:/usr/local/etc/haproxy/example.com.pem:ro # <4>
                networks:
                        - gateway # <5>
                        - mailcowdockerized_mailcow-network
                restart: unless-stopped
----
<1> Bind http(80) host port to haproxy docker container
<2> Bind https(443) host port to haproxy docker container
<3> Forward haproxy.cfg with read only access
<4> Forward example.com.pem to use SSL Termination in haproxy (more about this later)
<5> gateway is the docker network to reach the other containers

As you can see, all http/https requests are routed through HAProxy.

SSL Termination is the practice of terminating/decrypting an SSL connection at the load balancer, and sending unencrypted connections to the backend servers.


==== Seafile
Next we have *Seafile*, which in my oponion is far better than Nextcloud.
Nextcloud tries to provide everything but nothing reasonable. Just my two cents.

.docker-compose.yml
[source,yml]
----
        seafile:
                container_name: seafile
                image: seafileltd/seafile:latest
                volumes:
                        - ./seafile-shared:/shared:rw # <1>
                environment:
                        - SEAFILE_SERVER_HOSTNAME=sea.example.com # <2>
                networks:
                        - gateway
                restart: unless-stopped
----
<1> seafile-shared is the folder where seafile will store the data/config files
<2> this is the server hostname under which you can reach seafile later

Seafile is well documented, so as always I will just link it https://manual.seafile.com/deploy/deploy_with_docker.html[here].
There you can find how to modify Seafile Server Configuration and so on.

Since HAProxy takes care of SSL, Seafile does not need to do this.

==== Dynamic DNS 

This docker allows you to set up a dynamic DNS server that allows you to connect to devices at home from anywhere in the world.

With this container you can sent a API request from your router (FritzBox in my case) and then you can reach your home network e.g. at home.dyndns.example.com (this will be needed for later offsite backup).
How this goes you will find later under the subsection `Usage` or under the good documentation from https://github.com/dprandzioch/docker-ddns[dprandzioch @ Github].

.docker-compose.yml
[source,yml]
----
        ddns:
                image: davd/docker-ddns:latest
                ports:
                        - "53:53"
                        - "53:53/udp"
                networks:
                        - gateway
                environment:
                        RECORD_TTL: 60
                        ZONE: dyndns.example.com # <1>
                        SHARED_SECRET: changeme # <2>
                restart: unless-stopped
----
<1> is your dyndns domain (NS-Zone)
<2> SHARED_SECRET must be provided each time you update a DNS record via the API


==== Simple Welcome Webpage
I wrote a small website to get faster access to the subpages like SOGo from mailcow and seafile.
.docker-compose.yml
[source,yml]
----
         example_webpage:
                build:
                        context: ./example_welcome # <1>
                        dockerfile: Dockerfile
                networks:
                        - gateway
                restart: unless-stopped
----
<1> folder where the Dockerfile is placed (you can easly change this)

The index.html and Dockerfile is placed inside the example_welcome folder and should be self-explanatory.