= Complete Private Server Setup for E-Mail, Cloud and more
 
Here I describe my server setup, which provides the following services:

* E-Mail (https://mailcow.github.io/mailcow-dockerized-docs/[Mailcow])
* Cloud (https://www.seafile.com/en/home/[Seafile])
* Dynamic DNS (https://github.com/dprandzioch/docker-ddns[dprandzioch/docker-ddns @ Github])
* OpenVPN (https://github.com/kylemanna/docker-openvpn[kylemanna/docker-openvpn @ Github])
* Offside Backup (https://borgbackup.readthedocs.io/en/stable/[Borg Backup])
* A simple HTML Webpage

This Setup is set behind http://www.haproxy.org/[HAProxy] and https://letsencrypt.org/[LetsEncrypt]. And is deployed with https://docs.docker.com/[Docker] and https://docs.docker.com/compose/[Docker-Compose], to keep it as simple as possible.

I'm not a professional administrator and I run this setup privately only.

This is not supposed to be a copy&paste tutorial, but will probably work as such as well.

== Requirements

* Server with a static IP Address
* Domain
* Little Home Server for Offsite Backup (Raspberry PI/Intel Nuc/Hetzner Storagebox)

I'm using a VPS (virtual private server) from https://contabo.com/?show=vps[Contabo], called 'VPS L SSD' and a Intel NUC, both with Debian 10.

== Setup
=== Docker Installation

First we need to install Docker and Docker-Compose.
These steps are well documented on the official docker website, so I will just link to them.

https://docs.docker.com/install/linux/docker-ce/debian/[Docker]

https://docs.docker.com/compose/install/[Docker-Compose


=== Folder Structure and Preparation
Create folder structure (you can customize the location if you want) and download the required files.
[source,bash]
----
git clone https://github.com/oyren/yet_another_complete_groupware_setup /root/docker
git clone https://github.com/mailcow/mailcow-dockerized.git /root/docker/mailcow-dockerized
----


=== Configuration
Inside the `web` folder, you will find the `docker-compose.yml`.
I will split the files into parts to explain them, you have to replace `example.com` with your own domain and make other adjustments if necessary. 
.docker-compose.yml
[source,yml]
----
version: '3.5'
services:

        haproxy:
                container_name: haproxy
                image: haproxy:latest
                ports:
                        - "80:80" # <1>
                        - "443:443" # <2>
                volumes:
                        - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro # <3>
                        - ./example.com.pem:/usr/local/etc/haproxy/example.com.pem:ro # <4>
                networks:
                        - gateway # <5>
                        - mailcowdockerized_mailcow-network # <6>
                restart: unless-stopped
----
<1> Bind http(80) host port to haproxy docker container
<2> Bind https(443) host port to haproxy docker container
<3> Forward haproxy.cfg with read only access
<4> Forward example.com.pem to use SSL Termination in haproxy (more about this later)

As you can see, all http/https requests are routed through HAProxy.
SSL Termination is the practice of terminating/decrypting an SSL connection at the load balancer, and sending unencrypted connections to the backend servers.