:toc:
:toc-placement!:
:toclevels: 4
= Complete Private Server Setup for E-Mail, Cloud and more
 
Here I describe my server setup, which provides the following services:

* E-Mail (https://mailcow.github.io/mailcow-dockerized-docs/[Mailcow])
* Cloud (https://www.seafile.com/en/home/[Seafile])
* Dynamic DNS (https://github.com/dprandzioch/docker-ddns[dprandzioch/docker-ddns @ Github])
* OpenVPN (https://github.com/kylemanna/docker-openvpn[kylemanna/docker-openvpn @ Github])
* Offside Backup (https://borgbackup.readthedocs.io/en/stable/[Borg Backup])
* A simple HTML Webpage

This Setup is set behind http://www.haproxy.org/[HAProxy] and https://letsencrypt.org/[LetsEncrypt]. And is deployed with https://docs.docker.com/[Docker] and https://docs.docker.com/compose/[Docker-Compose], to keep it as simple as possible.

I'm not a professional administrator and I run this setup privately only.

This is not supposed to be a copy&paste tutorial, but will probably work as such as well.

toc::[]

== Requirements

* Server with a static IP Address
* Domain
* Little Home Server for Offsite Backup (Raspberry PI/Intel Nuc/Hetzner Storagebox)

I'm using a VPS (virtual private server) from https://contabo.com/?show=vps[Contabo], called 'VPS L SSD' and a Intel NUC, both with Debian 10.

== Setup
=== Docker installation

First we need to install Docker and Docker-Compose.
These steps are well documented on the official docker website, so I will just link to them.

https://docs.docker.com/install/linux/docker-ce/debian/[Docker]

https://docs.docker.com/compose/install/[Docker-Compose]

=== Let's Encrypt/Certbot installation
Just like with Docker, there are enough instructions to install https://certbot.eff.org/[certbot].

Inside `cli.ini`, we configure Let's Encrypt.

./etc/letsencrypt/cli.ini
[source,bash]
----
rsa-key-size = 4096
email = yourmail@example.com
authenticator = standalone
domains = example.com, www.example.com, sea.example.com, autoconfig.example.com, autodiscover.example.com, imap.example.com, mx.example.com, smtp.example.com, ns.example.com
----

IMPORTANT: Under the point domains, we enter the url's for which we want to have an SSL certificate.

=== Folder Structure and Preparation
Create folder structure (you can customize the location if you want) and download the required files.
[source,bash]
----
git clone https://github.com/oyren/yet_another_complete_groupware_setup /root/docker
git clone https://github.com/mailcow/mailcow-dockerized.git /root/docker/mailcow-dockerized
----


=== Configuration
Inside the `web` folder, you will find the `docker-compose.yml`.
I will split the files into parts to explain them, you have to replace `example.com` with your own domain and make other adjustments if necessary. 

==== HAProxy
Beginning with *HAProxy*, which we will use as a reserve proxy and which takes care of SSL.

.docker-compose.yml
[source,yml]
----
version: '3.5'
services:

        haproxy:
                container_name: haproxy
                image: haproxy:latest
                ports:
                        - "80:80" # <1>
                        - "443:443" # <2>
                volumes:
                        - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro # <3>
                        - ./example.com.pem:/usr/local/etc/haproxy/example.com.pem:ro # <4>
                networks:
                        - gateway # <5>
                        - mailcowdockerized_mailcow-network
                restart: unless-stopped
----
<1> Bind http(80) host port to haproxy docker container
<2> Bind https(443) host port to haproxy docker container
<3> Forward haproxy.cfg with read only access
<4> Forward example.com.pem to use SSL Termination in haproxy (more about this later)
<5> gateway is the docker network to reach the other containers

As you can see, all http/https requests are routed through HAProxy.

SSL Termination is the practice of terminating/decrypting an SSL connection at the load balancer, and sending unencrypted connections to the backend servers.

IMPORTANT: You also need to edit the `haproxy.cfg` (search for example.com and adjust it).

==== Seafile
Next we have *Seafile*, which in my opinion is far better than Nextcloud.
Nextcloud tries to provide everything but nothing reasonable. Just my two cents.

.docker-compose.yml
[source,yml]
----
        seafile:
                container_name: seafile
                image: seafileltd/seafile:latest
                volumes:
                        - ./seafile-shared:/shared:rw # <1>
                environment:
                        - SEAFILE_SERVER_HOSTNAME=sea.example.com # <2>
                networks:
                        - gateway
                restart: unless-stopped
----
<1> seafile-shared is the folder where seafile will store the data/config files
<2> this is the server hostname under which you can reach seafile later

Seafile is well documented, so as always I will just link it https://manual.seafile.com/deploy/deploy_with_docker.html[here].
There you can find how to modify Seafile Server Configuration and so on.

Since HAProxy takes care of SSL, Seafile does not need to do this.

==== Dynamic DNS 

This docker allows you to set up a dynamic DNS server that allows you to connect to devices at home from anywhere in the world.

With this container you can sent a API request from your router (FritzBox in my case) and then you can reach your home network e.g. at home.dyndns.example.com (this will be needed for later offsite backup).
How this goes you will find later under the subsection `Usage` or under the good documentation from https://github.com/dprandzioch/docker-ddns[dprandzioch @ Github].

.docker-compose.yml
[source,yml]
----
        ddns:
                image: davd/docker-ddns:latest
                ports:
                        - "53:53"
                        - "53:53/udp"
                networks:
                        - gateway
                environment:
                        RECORD_TTL: 60
                        ZONE: dyndns.example.com # <1>
                        SHARED_SECRET: changeme # <2>
                restart: unless-stopped
----
<1> is your dyndns domain (NS-Zone)
<2> SHARED_SECRET must be provided each time you update a DNS record via the API


==== Simple Welcome Webpage
I wrote a small website to get faster access to the subpages like SOGo from mailcow and seafile.
.docker-compose.yml
[source,yml]
----
         example_webpage:
                build:
                        context: ./example_welcome # <1>
                        dockerfile: Dockerfile
                networks:
                        - gateway
                restart: unless-stopped
----
<1> folder where the Dockerfile is placed (you can easily change this)

The index.html and Dockerfile is placed inside the example_welcome folder and should be self-explanatory.

==== Mailcow

You should have already cloned mailcow.

And renew we can use the already existing documentation.

First follow the Prerequisites:

* https://mailcow.github.io/mailcow-dockerized-docs/prerequisite-system/[Prepare Your System]

* https://mailcow.github.io/mailcow-dockerized-docs/prerequisite-dns/[DNS Setup]


Check if `umask` returns 0022.

Then follow the instructions starting at point 3:

* https://mailcow.github.io/mailcow-dockerized-docs/install/[Installation]

IMPORTANT: We use HAProxy as reserve proxy and to operate SSL, so there are some Important points in `mailcow.conf`, they are listed below. Skip `docker-compose up -d` for the moment.

.mailcow.conf
[source,bash]
----
HTTP_BIND=127.0.0.1
HTTP_PORT=8080
HTTPS_BIND=127.0.0.1
HTTPS_PORT=8443

ADDITIONAL_SAN=imap.example.com,smtp.example.com

# Skip running ACME (acme-mailcow, Let's Encrypt certs) - y/n
SKIP_LETS_ENCRYPT=y
----


==== DNS Records
This is how my DNS Records look like:
[source]
----
# Name                      Type        Value
example.com                 A           1.2.3.4
                            AAAA        2222:1111:3333::1
                            CAA         letsencrypt.org
                            MX          mx.example.com
                            TXT         "v=spf1 mx ~all"
autoconfig.example.com      A           1.2.3.4
                            AAAA        2222:1111:3333::1
autodiscover.example.com    A           1.2.3.4
                            AAAA        2222:1111:3333::1
dkim._domainkey.example.com TXT         v=DKIM1;k=rsa;t=s;s=email;p=....
dyndns.example.com          NS          ns.example.com
imap.example.com            A           1.2.3.4
                            AAAA        2222:1111:3333::1
mx.example.com              A           1.2.3.4
                            AAAA        2222:1111:3333::1
ns.example.com              A           1.2.3.4
                            AAAA        2222:1111:3333::1
sea.example.com             A           1.2.3.4
                            AAAA        2222:1111:3333::1
smtp.example.com            A           1.2.3.4
                            AAAA        2222:1111:3333::1
vpn.example.com             A           1.2.3.4
                            AAAA        2222:1111:3333::1
www.example.com             A           1.2.3.4
                            AAAA        2222:1111:3333::1
----

=== Get and renew SSL Certificate

IMPORTANT: Let's Encrypt certificates have a ninety-day lifetimes, so you have to renew them, before they expire.

You could run it through a cronjob regularly.

IMPORTANT: Also here you have to change `example.com` and the path if necessary.

[source,bash]
----
docker-compose -f /root/docker/mailcow-dockerized/docker-compose.yml down
docker-compose -f /root/docker/web/docker-compose.yml down
certbot certonly
cat /etc/letsencrypt/live/example.com/fullchain.pem /etc/letsencrypt/live/example.com/privkey.pem > /root/docker/web/example.com.pem
cp /etc/letsencrypt/live/example.com/fullchain.pem /root/docker/mailcow-dockerized/data/assets/ssl/cert.pem
cp /etc/letsencrypt/live/example.com/privkey.pem  /root/docker/mailcow-dockerized/data/assets/ssl/key.pem
docker-compose -f /root/docker/mailcow-dockerized/docker-compose.yml up -d
docker-compose -f /root/docker/web/docker-compose.yml up -d
----
As you can see the certificate will be copied at 2 places, once for haproxy and for mailcow.



=== Startup
[source,bash]
----
docker-compose -f /root/docker/mailcow-dockerized/docker-compose.yml up -d
docker-compose -f /root/docker/web/docker-compose.yml up -d
----

=== Backup